/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ua1jyAuwDga
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Taviraj } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import FeaturedPackage from "./FeaturedPackage"
import FeaturedBlogPost from "./FeaturedBlogPost"
import Hero from "./hero"

export function Home() {
  return (
    <div className="flex flex-col min-h-screen">
      <main className="flex-1">
        <Hero />
        <section className="py-12 md:py-16 lg:py-20" id="blog">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <div className="mb-8 md:mb-12 lg:mb-16">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold tracking-tight">Latest Blog Posts</h2>
              <p className="text-gray-600 dark:text-gray-400 text-lg md:text-xl lg:text-2xl">
                Check out my latest blog posts on web development and design.
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 md:gap-12 lg:gap-16">
              <Card>
                <CardHeader>
                  <img
                    alt="Blog Post 1"
                    className="rounded-t-lg"
                    height={200}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "400/200",
                      objectFit: "cover",
                    }}
                    width={400}
                  />
                </CardHeader>
                <CardContent>
                  <h3 className="text-xl md:text-2xl font-bold mb-2">Building a Responsive Web App with React</h3>
                  <p className="text-gray-600 dark:text-gray-400 mb-4">
                    In this blog post, I'll show you how to build a responsive web app using React and modern CSS
                    techniques.
                  </p>
                  <Link className="text-blue-500 hover:text-blue-600" href="#">
                    Read More
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <img
                    alt="Blog Post 2"
                    className="rounded-t-lg"
                    height={200}
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "400/200",
                      objectFit: "cover",
                    }}
                    width={400}
                  />
                </CardHeader>
                <CardContent>
                  <h3 className="text-xl md:text-2xl font-bold mb-2">Mastering CSS Grid Layout</h3>
                  <p className="text-gray-600 dark:text-gray-400 mb-4">
                    In this blog post, I'll dive deep into CSS Grid Layout and show you how to create complex layouts
                    with ease.
                  </p>
                  <Link className="text-blue-500 hover:text-blue-600" href="#">
                    Read More
                  </Link>
                </CardContent>
              </Card>
              <FeaturedBlogPost
                title="Building a Modern Website with Next.js"
                description="In this blog post, I'll show you how to build a modern website using Next.js and Tailwind CSS."
                url="#"
                likes={20}
                views={100}
                coverImage="https://cdn.hashnode.com/res/hashnode/image/stock/unsplash/jHZ70nRk7Ns/upload/366c91a3d458bbba7e65daeea32838d3.jpeg"
              />
            </div>
          </div>
        </section>
        <section className=" py-12 md:py-16 lg:py-20" id="packages">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <div className="mb-8 md:mb-12 lg:mb-16">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold tracking-tight">My Open-Source Packages</h2>
              <p className="text-gray-600 dark:text-gray-400 text-lg md:text-xl lg:text-2xl">
                Check out the open-source packages I've contributed to.
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 md:gap-12 lg:gap-16">
              <FeaturedPackage description="A modern and responsive website for a fictional company." title="Acme Inc" url="#" />
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20" id="websites">
          <div className="container mx-auto px-4 md:px-6 lg:px-8">
            <div className="mb-8 md:mb-12 lg:mb-16">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold tracking-tight">My Deployed Websites</h2>
              <p className="text-gray-600 dark:text-gray-400 text-lg md:text-xl lg:text-2xl">
                Check out some of the websites I've deployed.
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 md:gap-12 lg:gap-16">
              <Card>
                <CardHeader>
                  <h3 className="text-xl md:text-2xl font-bold mb-2">Acme Inc</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-600 dark:text-gray-400 mb-4">
                    A modern and responsive website for a fictional company.
                  </p>
                  <Link className="text-blue-500 hover:text-blue-600" href="#">
                    View Website
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <h3 className="text-xl md:text-2xl font-bold mb-2">Acme Inc</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-600 dark:text-gray-400 mb-4">
                    A modern and responsive website for a fictional company.
                  </p>
                  <Link className="text-blue-500 hover:text-blue-600" href="#">
                    View Website
                  </Link>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <h3 className="text-xl md:text-2xl font-bold mb-2">Acme Inc</h3>
                </CardHeader>
                <CardContent>
                  <p className="text-gray-600 dark:text-gray-400 mb-4">
                    A modern and responsive website for a fictional company.
                  </p>
                  <Link className="text-blue-500 hover:text-blue-600" href="#">
                    View Website
                  </Link>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
